### ISSUE TITLE
Wrong territory resolution for Switzerland

### ISSUE THREAD

**Issue by kstokoz** [mapcode-foundation/mapcode-java#23]
`Territory.fromString("CHE-GR")` result into `MX-GRO` territory where i would expect it result into CHE or throw UnknownTerritoryException.

**Comment by rijnb** [comment]
The issue has been confirmed. We'll look into this.

**Comment by rijnb** [comment]
OK. Here's what happened: the "state" GR does not exist in country CHE, so it is looked up in other other countries. Country MX has a state GRO, with alias GR. This is why MX-GR is matched instead.
We'll discuss this internally and see how we can improve the behavior of this API. Until then, we'll leave the issue open. Thanks for reporting.

**Comment by rijnb** [comment]
Fixed in release 2.2.3.
