### ISSUE TITLE
Are you planning to provide a JavaME/CLDC version based on Java 1.3/1.4?

### ISSUE THREAD

**Issue by ckrey** [mapcode-foundation/mapcode-java#9]

**Comment by MatthewLowden** [comment]
Hi ckrey,

No plans for a JavaME version right now. However please feel free to contact the foundation directly to discuss your use-case requiring JavaME.
You can contact the foundation at info@mapcode.com

Best Regards
Matt.

**Comment by rijnb** [comment]
(Thanks, Matt.) Indeed, no plans for JavaME. However, we are working on a version that moves back to Java 6 (from Java 8) to accommodate Android users.
And a Python version is available as well on: https://github.com/mapcode-foundation/mapcode-python

Regards,
-Rijn
Mapcode Foundation
